// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using caceis_aws_api.Data;

namespace caceis_aws_api.Migrations
{
    [DbContext(typeof(ModelDB))]
    partial class ArquivoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("caceis_aws_api.Models.Arquivo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("permitida")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Arquivo");
                });

            modelBuilder.Entity("caceis_aws_api.Models.Monitor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bucketDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bucketOrigem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataHoraFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataHoraInicia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomeArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoTransferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("transStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Monitor");
                });

            modelBuilder.Entity("caceis_aws_api.Models.Parceiros", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("autenticacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("autenticacaoId")
                        .HasColumnType("int");

                    b.Property<string>("chavePrivada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("conexaoHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("conexaoId")
                        .HasColumnType("int");

                    b.Property<string>("conexaoPorta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataDaAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dataDaCriacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senhaPrivada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Parceiros");
                });

            modelBuilder.Entity("caceis_aws_api.Models.Red", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("codClienteFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codClienteTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("palavraChave1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("palavraChave2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prefixo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Red");
                });

            modelBuilder.Entity("caceis_aws_api.Models.TipoAutenticacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TipoAutenticacao");
                });

            modelBuilder.Entity("caceis_aws_api.Models.TipoConexao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TipoConexao");
                });
#pragma warning restore 612, 618
        }
    }
}
